GET http://localhost:8000/order?offset=10&limit=10 HTTP/1.1
Host: localhost:8000
Content-Type: application/json

### Listar pedidos via GraphQL
POST http://localhost:8080/query
Content-Type: application/json

{
  "query": "query { listOrders(input: {offset: \"0\", limit: \"20\"}) { id Price Tax FinalPrice } }"
}